//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionSpaceBD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punto", Namespace="http://schemas.datacontract.org/2004/07/ConexionSpaceBD")]
    public partial class Punto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> DineroField;
        
        private int IdField;
        
        private System.Nullable<int> PuntuacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Dinero
        {
            get
            {
                return this.DineroField;
            }
            set
            {
                this.DineroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Puntuacion
        {
            get
            {
                return this.PuntuacionField;
            }
            set
            {
                this.PuntuacionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServicioSpace")]
public interface IServicioSpace
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSpace/RegistrarNuevoRecord", ReplyAction="http://tempuri.org/IServicioSpace/RegistrarNuevoRecordResponse")]
    bool RegistrarNuevoRecord(int dinero, int puntos);
    

    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSpace/ObtenerPuntos", ReplyAction="http://tempuri.org/IServicioSpace/ObtenerPuntosResponse")]
    ConexionSpaceBD.Punto[] ObtenerPuntos(int idPunto);
    
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServicioSpaceChannel : IServicioSpace, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServicioSpaceClient : System.ServiceModel.ClientBase<IServicioSpace>, IServicioSpace
{
    
    public ServicioSpaceClient()
    {
    }
    
    public ServicioSpaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServicioSpaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioSpaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioSpaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool RegistrarNuevoRecord(int dinero, int puntos)
    {
        return base.Channel.RegistrarNuevoRecord(dinero, puntos);
    }
    
    
    public ConexionSpaceBD.Punto[] ObtenerPuntos(int idPunto)
    {
        return base.Channel.ObtenerPuntos(idPunto);
    }
    
 
}
